package guru;

import config.DatabaseConnection;
import guru.FormData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ndita
 */
public class CariNilaiSiswa extends javax.swing.JFrame {
 int idUser;
 
    /**
     * Creates new form cariNilaiSiswa
     */
    public CariNilaiSiswa(int idUser) {
    super(); 
    initComponents();
    idUserLogin.setVisible(false);
    this.idUser = idUser;
    DefaultTableModel initialModel = new DefaultTableModel(
    new String [] {"NIS", "Kode Mapel", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "Nilai Rata-rata", "Status Kelulusan"}, 0
);
tblNilai.setModel(initialModel);
}

public CariNilaiSiswa() {
    super(); 
    initComponents();
    DefaultTableModel initialModel = new DefaultTableModel(
    new String [] {"NIS", "Kode Mapel", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "Nilai Rata-rata", "Status Kelulusan"}, 0
);
tblNilai.setModel(initialModel);
    // ...
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCari = new javax.swing.JButton();
        txtNis = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idUserLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCari.setBackground(new java.awt.Color(0, 204, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 78, -1, -1));
        getContentPane().add(txtNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 78, 269, -1));

        btnKembali.setBackground(new java.awt.Color(204, 204, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 342, -1, -1));

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 107, 503, 196));

        jLabel1.setText("Masukkan NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 56, -1, -1));
        getContentPane().add(idUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 378, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guru/background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        FormNilai form = new FormNilai(idUser); // ⬅️ gunakan variabel `idUser` yang sudah kamu simpan
        form.setVisible(true);
    // Optional: this.dispose(); jika ingin menutup halaman FiturGuru
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:                                       
    String nis = txtNis.getText().trim();

    if (nis.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan NIS terlebih dahulu.");
        return;
    }

    try (Connection conn = DatabaseConnection.getConnection()) {
        String sql = "SELECT nis, kd_mapel, nilai_tugas, nilai_uts, nilai_uas, nilai_rata, status_kelulusan FROM nilai WHERE nis = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, nis); // nis adalah nilai dari input pengguna
        ResultSet rs = stmt.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
        model.setRowCount(0); // Hapus data lama di tabel

        if (rs.next()) {
            String kdMapel = rs.getString("kd_mapel");
            double nilaiTugas = rs.getDouble("nilai_tugas");
            double nilaiUTS = rs.getDouble("nilai_uts");
            double nilaiUAS = rs.getDouble("nilai_uas");
            double nilaiRata = rs.getDouble("nilai_rata");
            String status = rs.getString("status_kelulusan");

            model.addRow(new Object[]{nis, kdMapel, nilaiTugas, nilaiUTS, nilaiUAS, nilaiRata, status});
        } else {
            JOptionPane.showMessageDialog(this, "Data nilai dengan NIS tersebut tidak ditemukan.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data nilai.");
    }

    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel idUserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtNis;
    // End of variables declaration//GEN-END:variables
}
