package guru;







/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ndita
 */
import guru.FormData;
import config.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CariDataSiswa extends javax.swing.JFrame {
private int idUserLogin;
    /**
     * Creates new form CariDataSiswa
     */
    public CariDataSiswa() {
        initComponents();
        
        this.idUserLogin=idUserLogin;
         String[] kolom = {"NIS", "Nama", "Jenis Kelamin", "Kelas"};
    DefaultTableModel model = new DefaultTableModel(kolom, 0);
    tblSiswa.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNIS = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNISActionPerformed(evt);
            }
        });
        getContentPane().add(txtNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 84, 184, -1));

        btnCari.setBackground(new java.awt.Color(0, 204, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 84, -1, -1));

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 125, 498, 164));

        btnKembali.setBackground(new java.awt.Color(204, 204, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 325, -1, -1));

        jLabel1.setText("Masukkan NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 62, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guru/background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String nis = txtNIS.getText().trim();

    if (nis.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan NIS terlebih dahulu.");
        return;
    }

  try (Connection conn = DatabaseConnection.getConnection()) {
    String sql = "SELECT nis, nama_siswa, jenis_kelamin, kelas FROM siswa WHERE nis = ?";
    PreparedStatement stmt = conn.prepareStatement(sql);
    stmt.setString(1, nis); // nis adalah nilai dari input pengguna
    ResultSet rs = stmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) tblSiswa.getModel();
    model.setRowCount(0); // Hapus data lama di tabel

    if (rs.next()) {
        String nama = rs.getString("nama_siswa");
        String jk = rs.getString("jenis_kelamin");
        String kelas = rs.getString("kelas");

        model.addRow(new Object[]{nis, nama, jk, kelas});
    } else {
        JOptionPane.showMessageDialog(this, "Siswa dengan NIS tersebut tidak ditemukan.");
    }
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data.");
}

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
      new FormData(idUserLogin).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNISActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextField txtNIS;
    // End of variables declaration//GEN-END:variables
}
