package guru;


import interfaces.NilaiSiswaInterface;
import guru.CariNilaiSiswa;
import guru.FiturGuru;
import guru.KelolaNilaiSiswa;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ndita
 */
public class FormNilai extends javax.swing.JFrame implements NilaiSiswaInterface{
private int idUserLogin;
    /**
     * Creates new form FormNilai
     */
     public FormNilai(int idUserLogin) {
        this.idUserLogin = idUserLogin; // Menetapkan ID yang diteruskan ke field
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCariSiswa = new javax.swing.JButton();
        btnIsiNilaiSiswa = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCariSiswa.setBackground(new java.awt.Color(0, 204, 255));
        btnCariSiswa.setText("Cari Nilai Siswa");
        btnCariSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariSiswaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 137, -1));

        btnIsiNilaiSiswa.setBackground(new java.awt.Color(0, 204, 255));
        btnIsiNilaiSiswa.setText("Isi Nilai Siswa");
        btnIsiNilaiSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiNilaiSiswaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIsiNilaiSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 137, -1));

        btnKembali.setBackground(new java.awt.Color(204, 204, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guru/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariSiswaActionPerformed
         new CariNilaiSiswa().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnCariSiswaActionPerformed

    private void btnIsiNilaiSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiNilaiSiswaActionPerformed
       new KelolaNilaiSiswa().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnIsiNilaiSiswaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
        
        new FiturGuru(idUserLogin).setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariSiswa;
    private javax.swing.JButton btnIsiNilaiSiswa;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void simpanData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void updateData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void hapusData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void hitungNilai() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
