package guru;


import guru.KelolaDataSiswa;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ndita
 */
public class FormData extends javax.swing.JFrame {
    int idUserLogin;
    /**
     * Creates new form FormGuru
     */
    public FormData(int idUserLogin) {
        this.idUserLogin = idUserLogin;
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCariDataSiswa = new javax.swing.JButton();
        btnTambahData = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCariDataSiswa.setBackground(new java.awt.Color(0, 204, 255));
        btnCariDataSiswa.setText("Cari Data Siswa");
        btnCariDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataSiswaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariDataSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 130, -1));

        btnTambahData.setBackground(new java.awt.Color(0, 204, 255));
        btnTambahData.setText("Isi Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 130, -1));

        btnKembali.setBackground(new java.awt.Color(204, 204, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guru/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataSiswaActionPerformed
 new CariDataSiswa().setVisible(true); // Pastikan variabel idUserLogin bertipe int

   
    this.dispose();     
    }//GEN-LAST:event_btnCariDataSiswaActionPerformed

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
    new KelolaDataSiswa(idUserLogin).setVisible(true); // Pastikan variabel idUserLogin bertipe int

   
    this.dispose(); 
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
        
         FiturGuru menu = new FiturGuru(idUserLogin);
    menu.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariDataSiswa;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
