/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siswa;

import config.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.Login;

/**
 *
 * @author LENOVO
 */
public class FiturSiswa extends javax.swing.JFrame {
    private int idUserLogin;
    
   
    /**
     * Creates new form FiturSiswa
     */
    public FiturSiswa() {
        this.setExtendedState(FiturSiswa.MAXIMIZED_BOTH);
        initComponents();
        this.idUserLogin = idUserLogin;
        setupTableColumns();
        
        jLabel2.setText("Selamat datang!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTampil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNilai = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 69, 226, -1));

        jLabel1.setText("Masukkan NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 47, -1, -1));

        btnTampil.setBackground(new java.awt.Color(0, 204, 255));
        btnTampil.setText("Tampilkan");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 69, -1, -1));

        tableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNilai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 570, 230));

        btnLogout.setBackground(new java.awt.Color(0, 204, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guru/background.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true); // Pastikan form login Anda bernama LoginForm
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        TampilkanNilai();
    }//GEN-LAST:event_btnTampilActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void setupTableColumns() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID User");
        model.addColumn("NIS");
        model.addColumn("Kode Mapel");
        model.addColumn("Nilai Tugas");
        model.addColumn("Nilai UTS");
        model.addColumn("Nilai UAS");
        model.addColumn("Nilai Rata-Rata");
        model.addColumn("Status Kelulusan");
        tableNilai.setModel(model);
    }
    
    private void TampilkanNilai() {
        String nisDicari = txtNis.getText().trim();

        if (nisDicari.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan NIS yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tableNilai.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum mengisi data baru

        String sql = "SELECT id_user, nis, kd_mapel, nilai_tugas, nilai_uts, nilai_uas, nilai_rata, status_kelulusan " +
                     "FROM nilai WHERE nis = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, nisDicari); // Mengatur parameter NIS
            ResultSet rs = pst.executeQuery();

            boolean found = false;
            while (rs.next()) {
                found = true;
                Object[] row = new Object[8];
                row[0] = rs.getInt("id_user");
                row[1] = rs.getString("nis");
                row[2] = rs.getString("kd_mapel");
                row[3] = rs.getDouble("nilai_tugas");
                row[4] = rs.getDouble("nilai_uts");
                row[5] = rs.getDouble("nilai_uas");
                row[6] = rs.getDouble("nilai_rata");
                row[7] = rs.getString("status_kelulusan");
                model.addRow(row);
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Data nilai untuk NIS '" + nisDicari + "' tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat mencari data: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Cetak stack trace untuk debugging lebih lanjut
        }
    }
    
    private void loadAllNilaiData() {
        DefaultTableModel model = (DefaultTableModel) tableNilai.getModel();
        model.setRowCount(0); // Kosongkan tabel

        String sql = "SELECT id_user, nis, kd_mapel, nilai_tugas, nilai_uts, nilai_uas, nilai_rata, status_kelulusan FROM nilai";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getInt("id_user");
                row[1] = rs.getString("nis");
                row[2] = rs.getString("kd_mapel");
                row[3] = rs.getDouble("nilai_tugas");
                row[4] = rs.getDouble("nilai_uts");
                row[5] = rs.getDouble("nilai_uas");
                row[6] = rs.getDouble("nilai_rata");
                row[7] = rs.getString("status_kelulusan");
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat memuat semua data nilai: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNilai;
    private javax.swing.JTextField txtNis;
    // End of variables declaration//GEN-END:variables
}
